### PR TITLE
feat: Yahtzee dice game for fCC's v7.0 curriculum

### PR DESCRIPTION
**Pull request by vkWeb**
I have made the following changes:
- refactored the whole game from scratch
- implemented logic as per original Yahtzee game with some modifications to make it simple
- revamped UI for better UX

@perezvon I think I'm close to finishing this up. So I thought your input will help in improving the program design. This project should be a masterpiece 🔥 because it's one of the most critical sections of the curriculum. We need to refine, optimize and clean this project as it's going to impact millions of future coders.  

So I'll be looking forward to your feedback on the code, program design, and UI as well ;)

### CODE REVIEW

**Comment by vkWeb** [comment]
@perezvon we will together work on the below TO DOs:
- [ ] Implement score history in `updateUI()`
- [ ] change `getNumOfTotalConsecutives` logic to return maximum number of consecutives. Suppose the input is `[1, 2, 3, 6, 7, 8, 9]` so there are two sets of consecutives (3 and 4 consecutives). The output should be 4, not 3. The current implementation is fine for our input cases but I want to make it generic.
- [ ] implement `const getSameArrElements = (arrToSearch, arrSearchItems) => {};` as binary search
- [ ] clean the codebase, better program design, better UI

**Comment by vkWeb** [comment]
@perezvon Also please host this on GitHub pages so that we can get feedback from the community. Thanks.

**Comment by shynonagons** [comment]
@vkWeb Awesome, thanks! Huge improvements. 

It looks like the small straight isn't being detected anymore, (possibly the large too but haven't rolled one 🙂 ) 

I should have some time later today / tonight to get more work done on this.

**Comment by vkWeb** [comment]
@perezvon Yes, you are right straights aren't getting detected. Also, the total score is NaN. We can fix these up in our next improvement iteration.

**Comment by shynonagons** [comment]
Indeed! Also the game is up at https://perezvon.github.io/fcc-dice-game/ now

**Pull request merged**
