### PR TITLE
Refactored updateUI function to take currentScore as an arg

### PR DESCRIPTION
**Pull request by shynonagons**
This allows the UI to be updated when a new score is available, instead of being cleared and rerendered on each click.

### CODE REVIEW

**Comment by vkWeb** [comment]
@perezvon I think we can approach this in a better way. To do that we will need to make some foundational change to the way we store score history in `game.scoreHistory`. 

Here's what we should do:

1. `game.scoreHistory` should be an array instead of object.
2. Push an object to `scoreHistory` in format `"score-option": score-value`. 
Like `[{"chance": 12}, {"none": 0}]`. This approach will allow duplicates and will also maintain the order of scores.
3. Use the latest pushed value to print it on screen like `Object.keys(scoreHistory[scoreHistory.length - 1])[0]`.

**Comment by vkWeb** [comment]
@perezvon I have resolved the merge conflicts. Now you can make changes according to my suggestions.

**Comment by vkWeb** [comment]
@perezvon any updates brother?

**Comment by shynonagons** [comment]
@vkWeb Yes, I agree with this proposal 100%, changes made and ready to go

**Comment by vkWeb** [comment]
@perezvon Thanks! I did some updates and merged.

**Pull request merged**
